/*
 * SQL Setup Script for Wazuh Alert Storage
 *
 * Creates the PLCSecurityAlerts table in the prt_unified database
 * for storing correlated alerts generated by the Wazuh SIEM manager.
 *
 * These are DISTINCT from PLCSecurityLogs (raw events from PLCSecurityMonitor).
 * PLCSecurityAlerts contain enriched, correlated alerts that have been processed
 * through Wazuh's rule engine -- e.g., "3 mode changes in 5 minutes = attack pattern."
 *
 * Run this script after setup_plc_security_logs.sql:
 *   mysql -u root -p prt_unified < setup_plc_security_alerts.sql
 */

USE prt_unified;

-- ============================================================================
-- WAZUH SECURITY ALERTS TABLE
-- Stores correlated/enriched alerts from the Wazuh SIEM manager
-- ============================================================================

CREATE TABLE IF NOT EXISTS PLCSecurityAlerts (
    id INT AUTO_INCREMENT PRIMARY KEY,

    -- Wazuh Alert Identification
    wazuh_alert_id VARCHAR(100) NOT NULL,          -- Unique ID (timestamp_ruleId_agentId)
    wazuh_rule_id VARCHAR(20) NOT NULL,            -- Rule ID that fired (e.g., "100021")
    wazuh_rule_level INT NOT NULL,                 -- Wazuh severity level (0-15)
    wazuh_rule_description VARCHAR(500) NOT NULL,  -- Description from rule definition
    wazuh_rule_groups TEXT DEFAULT NULL,            -- Comma-separated groups (e.g., "plc_security,mode_change")

    -- Wazuh Agent Information
    agent_id VARCHAR(20) DEFAULT NULL,             -- Wazuh agent ID (e.g., "001")
    agent_name VARCHAR(100) DEFAULT NULL,          -- Agent name (e.g., "prt-backend")
    agent_ip VARCHAR(50) DEFAULT NULL,             -- Agent IP address

    -- Original Event Data (from the data.* fields in alerts.json)
    plc_ip VARCHAR(50) DEFAULT NULL,               -- PLC IP from original event
    event_type VARCHAR(50) DEFAULT NULL,           -- MODE_CHANGE, FAULT, CONNECTION, etc.
    severity VARCHAR(20) DEFAULT NULL,             -- Severity from original event
    event_message VARCHAR(500) DEFAULT NULL,       -- Message from original event
    previous_state VARCHAR(100) DEFAULT NULL,      -- Previous state (for change events)
    current_state VARCHAR(100) DEFAULT NULL,       -- Current state

    -- Full Alert Storage
    raw_alert TEXT NOT NULL,                       -- Complete Wazuh alert JSON for forensics

    -- Alert Management
    acknowledged TINYINT(1) NOT NULL DEFAULT 0,    -- Whether operator has acknowledged
    acknowledged_by VARCHAR(100) DEFAULT NULL,      -- Who acknowledged it
    acknowledged_at DATETIME DEFAULT NULL,          -- When it was acknowledged

    -- Timestamps
    wazuh_timestamp DATETIME NOT NULL,             -- When Wazuh generated the alert
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- When we stored it

    -- Indexes
    UNIQUE INDEX idx_wazuh_alert_id (wazuh_alert_id),
    INDEX idx_rule_id (wazuh_rule_id),
    INDEX idx_rule_level (wazuh_rule_level),
    INDEX idx_plc_ip (plc_ip),
    INDEX idx_event_type (event_type),
    INDEX idx_acknowledged (acknowledged),
    INDEX idx_wazuh_timestamp (wazuh_timestamp),
    INDEX idx_ingested_at (ingested_at)
);

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT 'PLCSecurityAlerts table created!' AS message;
DESCRIBE PLCSecurityAlerts;
