/*
 * SQL Setup Script for PLC Security Alerts
 *
 * Creates the PLCSecurityAlerts table in the prt_unified database
 * for storing correlated security alerts generated by the CorrelationEngine.
 *
 * These are DISTINCT from PLCSecurityLogs (raw events from PLCSecurityMonitor).
 * PLCSecurityAlerts contain correlated alerts that detect attack patterns --
 * e.g., "3 mode changes in 5 minutes = possible attack."
 *
 * Run this script after setup_plc_security_logs.sql:
 *   mysql -u root -p prt_unified < setup_plc_security_alerts.sql
 */

USE prt_unified;

-- Drop old version if it exists (safe to re-run)
DROP TABLE IF EXISTS PLCSecurityAlerts;

-- ============================================================================
-- PLC SECURITY ALERTS TABLE
-- Stores correlated alerts from the SQL-based CorrelationEngine
-- ============================================================================

CREATE TABLE IF NOT EXISTS PLCSecurityAlerts (
    id INT AUTO_INCREMENT PRIMARY KEY,

    -- Alert Identification
    alert_id VARCHAR(100) NOT NULL,              -- Dedup key: rule_id + plc_ip + time_window
    rule_id VARCHAR(20) NOT NULL,                -- Correlation rule (CORR_001, CORR_002, CORR_003)
    rule_level INT NOT NULL,                     -- Severity level (0-15 scale)
    rule_description VARCHAR(500) NOT NULL,      -- Human-readable description

    -- Event Context
    plc_ip VARCHAR(50) DEFAULT NULL,             -- PLC IP from correlated events
    event_type VARCHAR(50) DEFAULT NULL,         -- MODE_CHANGE, CONNECTION, FAULT, etc.
    severity VARCHAR(20) DEFAULT NULL,           -- Severity from correlated events
    event_message VARCHAR(500) DEFAULT NULL,     -- Summary message

    -- Correlation Details
    matched_event_count INT DEFAULT NULL,        -- Number of events that triggered this alert
    time_window_seconds INT DEFAULT NULL,        -- Time window used for detection
    matched_log_ids TEXT DEFAULT NULL,           -- CSV of PLCSecurityLogs.id values

    -- Alert Management
    acknowledged TINYINT(1) NOT NULL DEFAULT 0,  -- Whether operator has acknowledged
    acknowledged_by VARCHAR(100) DEFAULT NULL,   -- Who acknowledged it
    acknowledged_at DATETIME DEFAULT NULL,       -- When it was acknowledged

    -- Timestamps
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- When the correlation engine detected it

    -- Indexes
    UNIQUE INDEX idx_alert_id (alert_id),
    INDEX idx_rule_id (rule_id),
    INDEX idx_rule_level (rule_level),
    INDEX idx_plc_ip (plc_ip),
    INDEX idx_acknowledged (acknowledged),
    INDEX idx_detected_at (detected_at)
);

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT 'PLCSecurityAlerts table created!' AS message;
DESCRIBE PLCSecurityAlerts;
