FROM fdamador/openplc:latest

# OpenPLC runtime for PRT
# Ports: Modbus (502), EtherNet/IP (44818), Web (8080)

EXPOSE 502 44818 8080

# TODO: Add your ladder logic programs to /opt/openplc/programs/
# See README.md for instructions